### ISSUE TITLE
Bad URL in Readme

### ISSUE THREAD

**Issue by avallesalas** [AjuntamentdeBarcelona/agile-methodologies-bcn-en#1]
The URL in the title metadata points to a "Not Found" error

https://www.barcelona.cat/digitalstandards/en/agile-methodologies/

**Comment by gmarpons** [comment]
Good catch, thanks!

Fixed in https://github.com/AjuntamentdeBarcelona/ethical-digital-standards-site/commit/609e12156549eba7c93c26bbdab38f8f1a6f07d9.
